{{- if .Values.database.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ include "ai-hub-manifest.targetNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name }}
    app.kubernetes.io/component: database
    {{- include "ai-hub-manifest.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.database.instances }}
  imageName: {{ .Values.database.imageName }}
  bootstrap:
    initdb:
      database: {{ .Values.database.initdb.database }}
      owner: {{ .Values.database.initdb.owner }}
  storage:
    size: {{ .Values.database.storage.size }}
{{- if .Values.database.monitoring.enabled }}
  monitoring:
    enablePodMonitor: false  # PodMonitor를 별도로 생성하므로 false
{{- end }}
{{- if .Values.database.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.database.backup.retentionPolicy }}
    barmanObjectStore:
      serverName: {{ .Values.database.name }}
      destinationPath: s3://{{ .Values.database.backup.r2.bucketName }}/
      endpointURL: {{ .Values.database.backup.r2.endpoint }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.database.backup.r2.existingSecretName }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.database.backup.r2.existingSecretName }}
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
{{- end }}

{{- if .Values.database.backup.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.database.name }}-daily-backup
  namespace: {{ include "ai-hub-manifest.targetNamespace" . }}
spec:
  schedule: "0 0 21 * * *"
  immediate: true
  cluster:
    name: {{ .Values.database.name }}
{{- end }}

{{- if and .Values.database.monitoring.enabled .Values.database.monitoring.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.database.name }}-monitor
  namespace: {{ include "ai-hub-manifest.targetNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name }}
    app.kubernetes.io/component: database
    {{- include "ai-hub-manifest.labels" . | nindent 4 }}
    {{- with .Values.database.monitoring.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.database.name }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.database.monitoring.podMonitor.interval }}
      scrapeTimeout: {{ .Values.database.monitoring.podMonitor.scrapeTimeout }}
{{- end }}

{{- end }}